#!/bin/bash
#Common config routines for nodezero


_NzCheckRoot() { #Check if we are root
if [[ "$(/usr/bin/whoami)" != "root" ]]; then
    echo "This script must be run as root\! Script aborted."
    exit 1
fi
}


_NzListFunctions() { #List all available Nodezero shell scripts
grep -roh "^_.*()" $NZ_PATH/scripts/
}


_NzEditConfig() { #Edit and reload main nodezero config file
    #Note: See also https://packages.debian.org/sid/augeas-tools to edit config files
    $EDITOR ${NZ_CONF_PATH}/nodezero.conf
    source "${NZ_CONF_PATH}/nodezero.conf"
    _NzReloadConfig #TODO: (check if paths/values in nodezero.conf are valid) update config files accordingly
}

_NzReloadConfig() { #Main config reload routine
	_NzConfigUpdateFqdn
	_NzRegenContactPage
}

_NzConfigUpdateFqdn() {
	echo "$NZ_FQDN" >| /etc/hostname
	hostname "$NZ_FQDN"
}

_NzRegenContactPage() { #Generate web server contact page
ContactAddresses=""
if -z "$NZ_PUBLIC_MAIL"; then ContactAddresses="$ContactAddresses \n <a data-toggle=\"tooltip\" title=\"Email\" href=\"$NZ_PUBLIC_MAIL\"><i class=\"icon-mail-alt\"></i></a>"; fi
if -z "$NZ_PUBLIC_IM"; then ContactAddresses="$ContactAddresses \n <a data-toggle=\"tooltip\" title=\"IM\" href=\"$NZ_PUBLIC_IM\"><i class=\"icon-comment\"></i></a>"; fi
if -z "$NZ_PUBLIC_PHONE"; then ContactAddresses="$ContactAddresses \n <a data-toggle=\"tooltip\" title=\"Git\" href=\"$NZ_PUBLIC_PHONE\"><i class=\"icon-phone-squared\"></i></a>"; fi
if -z "$NZ_PUBLIC_TWITTER"; then ContactAddresses="$ContactAddresses \n <a data-toggle=\"tooltip\" title=\"Twitter\" href=\"$Z_PUBLIC_TWITTER\"><i class=\"icon-twitter-squared\"></i></a>"; fi
if -z "$NZ_PUBLIC_GPLUS"; then ContactAddresses="$ContactAddresses \n <a data-toggle=\"tooltip\" title=\"Google+\" href=\"$NZ_PUBLIC_GPLUS\"><i class=\"icon-gplus-squared\"></i></a>"; fi
if -z "$NZ_PUBLIC_FACEBOOK"; then ContactAddresses="$ContactAddresses \n <a data-toggle=\"tooltip\" title=\"Facebook\" href=\"$NZ_PUBLIC_FACEBOOK\"><i class=\"icon-facebook-squared\"></i></a>"; fi
if -z "$NZ_PUBLIC_TUMBLR"; then ContactAddresses="$ContactAddresses \n <a data-toggle=\"tooltip\" title=\"Tumblr\" href=\"$NZ_PUBLIC_TUMBLR\"><i class=\"icon-tumblr-squared\"></i></a>"; fi
if -z "$NZ_PUBLIC_INSTAGRAM"; then ContactAddresses="$ContactAddresses \n <a data-toggle=\"tooltip\" title=\"Instagram\" href=\"$NZ_PUBLIC_INSTAGRAM\"><i class=\"icon-instagramm\"></i></a>"; fi
if -z "$NZ_PUBLIC_YOUTUBE"; then ContactAddresses="$ContactAddresses \n <a data-toggle=\"tooltip\" title=\"Youtube\" href=\"$NZ_PUBLIC_YOUTUBE\"><i class=\"icon-youtube-play\"></i></a>"; fi
if -z "$NZ_PUBLIC_GITHUB"; then ContactAddresses="$ContactAddresses \n <a data-toggle=\"tooltip\" title=\"Github\" href=\"$NZ_PUBLIC_GITHUB\"><i class=\"icon-github-squared\"></i></a>"; fi
if -z "$NZ_PUBLIC_LINKEDIN"; then ContactAddresses="$ContactAddresses \n <a data-toggle=\"tooltip\" title=\"LinkedIn\" href=\"$NZ_PUBLIC_LINKEDIN\"><i class=\"icon-linkedin-squared\"></i></a>"; fi
if -z "$NZ_PUBLIC_SKYPE"; then ContactAddresses="$ContactAddresses \n <a data-toggle=\"tooltip\" title=\"Skype\" href=\"$NZ_PUBLIC_SKYPE\"><i class=\"icon-skype\"></i></a>"; fi
if -z "$NZ_PUBLIC_BTC"; then ContactAddresses="$ContactAddresses \n <a data-toggle=\"tooltip\" title=\"Bitcoin\" href=\"$NZ_PUBLIC_BTC\"><i class=\"icon-bitcoin\"></i></a>"; fi
if -z "$NZ_PUBLIC_MISC"; then ContactAddresses="$ContactAddresses \n <a data-toggle=\"tooltip\" title=\"Misc\" href=\"$NZ_PUBLIC_MISC\"><i class=\"icon-blank\"></i></a>"; fi
#TODO: create webpage by concatenating HTML header + $ContactAddresses + footer, then write it to contact/index.html
cat $NZ_PATH/contact/header.html "$ContactAddresses" $NZ_PATH/contact/footer.html > $APACHE_DOCUMENTROOT/contact/index.html
_NzSetWwwPermissions
}

_NzSymlinkWebappDataDirs() { #Create symlinks to zenphoto and Dokuwiki data dirs in the main user's (UID 1000) home directory
	echo "Not yet implemented." #TODO: Not called from anywhere, add this to a menu
}


_NzUserGetName() { #Get system's main user name (assume it was the first user created)
	NZ_USER=$(getent passwd|grep 1000:1000|awk -F":" '{print $1}')
}