#!/bin/bash
#Description: Common config routines for nodezero (https://telecom.dmz.se/software/nodezero)
#Copyright (c) 2014 nodiscc
#License: MIT (http://opensource.org/licenses/MIT)
# ░░░░░█▀█
# ░░░░░█░█
# ░▀▀▀░▀▀▀



_NzCheckRoot() { #Check if we are root
if [[ "$(/usr/bin/whoami)" != "root" ]]; then
    echo "This script must be run as root\! Script aborted."
    exit 1
fi
}


_ArrayContainsElement () { #thanks https://stackoverflow.com/questions/3685970/
  local e
  for e in "${@:2}"; do [[ "$e" == "$1" ]] && return 0; done
  return 1
}

_NzListFunctions() { #List all available Nodezero shell scripts
grep -roh "^_.*()" $NZ_PATH/scripts/
}


_NzEditConfig() { #Edit and reload main nodezero config file
    #Note: See also https://packages.debian.org/sid/augeas-tools to edit config files
    $EDITOR ${NZ_CONF_PATH}/nodezero.conf
    source "${NZ_CONF_PATH}/nodezero.conf"
    _NzReloadConfig #TODO: (check if paths/values in nodezero.conf are valid) update config files accordingly
}

_NzReloadConfig() { #Main config reload routine
	_NzConfigUpdateFqdn
	_NzRegenContactPage
	_NzRegenHomePage
	_NzFixPermissions
}

_NzConfigUpdateFqdn() {
	echo "$NZ_FQDN" >| /etc/hostname
	hostname "$NZ_FQDN"
}


_NzFixPermissions() { #Fix permissions for transmission/apache files
    chown debian-transmission:debian-transmission /var/log/debian-transmission.log
    chown -R debian-transmission:debian-transmission ${transmission_download_dir}
    chown daemon:daemon /var/log/debsecan
    chown -R "$NZ_USER":"$APACHE_GROUP" "$APACHE_DOCUMENTROOT"
    find "$APACHE_DOCUMENTROOT" -type d -print0 | xargs -0 chmod 750
    find "$APACHE_DOCUMENTROOT" -type f -print0 | xargs -0 chmod 640
    chmod -R g+w /var/www/links/{data,pagecache,cache,tmp}/ \
    	/var/www/bugs/{.htaccess,database} \
    	/var/www/tt-rss/{cache/export/,cache/images/,feed-icons/,lock/,cache/upload/,cache/js/}
    chmod 600 /etc/ssl/private/ssl-cert-snakeoil.key
}

_NzRegenContactPage() { #Generate web server contact page
	ContactAddresses=""
	if [ ! -z "$NZ_PUBLIC_MAIL" ]; then ContactAddresses="$ContactAddresses \n <a data-toggle=\"tooltip\" title=\"Email\" href=\"mailto:$NZ_PUBLIC_MAIL\"><i class=\"icon-mail-alt\"></i></a>"; fi
	if [ ! -z "$NZ_PUBLIC_IM" ]; then ContactAddresses="$ContactAddresses \n <a data-toggle=\"tooltip\" title=\"IM\" href=\"xmpp:$NZ_PUBLIC_IM\"><i class=\"icon-comment\"></i></a>"; fi
	if [ ! -z "$NZ_PUBLIC_PHONE" ]; then ContactAddresses="$ContactAddresses \n <a data-toggle=\"tooltip\" title=\"Git\" href=\"$NZ_PUBLIC_PHONE\"><i class=\"icon-phone-squared\"></i></a>"; fi
	if [ ! -z "$NZ_PUBLIC_TWITTER" ]; then ContactAddresses="$ContactAddresses \n <a data-toggle=\"tooltip\" title=\"Twitter\" href=\"https://twitter.com/$NZ_PUBLIC_TWITTER\"><i class=\"icon-twitter-squared\"></i></a>"; fi
	if [ ! -z "$NZ_PUBLIC_GPLUS" ]; then ContactAddresses="$ContactAddresses \n <a data-toggle=\"tooltip\" title=\"Google+\" href=\"$NZ_PUBLIC_GPLUS\"><i class=\"icon-gplus-squared\"></i></a>"; fi
	if [ ! -z "$NZ_PUBLIC_FACEBOOK" ]; then ContactAddresses="$ContactAddresses \n <a data-toggle=\"tooltip\" title=\"Facebook\" href=\"$NZ_PUBLIC_FACEBOOK\"><i class=\"icon-facebook-squared\"></i></a>"; fi
	if [ ! -z "$NZ_PUBLIC_TUMBLR" ]; then ContactAddresses="$ContactAddresses \n <a data-toggle=\"tooltip\" title=\"Tumblr\" href=\"$NZ_PUBLIC_TUMBLR\"><i class=\"icon-tumblr-squared\"></i></a>"; fi
	if [ ! -z "$NZ_PUBLIC_INSTAGRAM" ]; then ContactAddresses="$ContactAddresses \n <a data-toggle=\"tooltip\" title=\"Instagram\" href=\"$NZ_PUBLIC_INSTAGRAM\"><i class=\"icon-instagramm\"></i></a>"; fi
	if [ ! -z "$NZ_PUBLIC_YOUTUBE" ]; then ContactAddresses="$ContactAddresses \n <a data-toggle=\"tooltip\" title=\"Youtube\" href=\"$NZ_PUBLIC_YOUTUBE\"><i class=\"icon-youtube-play\"></i></a>"; fi
	if [ ! -z "$NZ_PUBLIC_GITHUB" ]; then ContactAddresses="$ContactAddresses \n <a data-toggle=\"tooltip\" title=\"Github\" href=\"https://github.com/$NZ_PUBLIC_GITHUB\"><i class=\"icon-github-squared\"></i></a>"; fi
	if [ ! -z "$NZ_PUBLIC_LINKEDIN" ]; then ContactAddresses="$ContactAddresses \n <a data-toggle=\"tooltip\" title=\"LinkedIn\" href=\"$NZ_PUBLIC_LINKEDIN\"><i class=\"icon-linkedin-squared\"></i></a>"; fi
	if [ ! -z "$NZ_PUBLIC_SKYPE" ]; then ContactAddresses="$ContactAddresses \n <a data-toggle=\"tooltip\" title=\"Skype\" href=\"$NZ_PUBLIC_SKYPE\"><i class=\"icon-skype\"></i></a>"; fi
	if [ ! -z "$NZ_PUBLIC_BTC" ]; then ContactAddresses="$ContactAddresses \n <a data-toggle=\"tooltip\" title=\"Bitcoin\" href=\"$NZ_PUBLIC_BTC\"><i class=\"icon-bitcoin\"></i></a>"; fi
	if [ ! -z "$NZ_PUBLIC_MISC" ]; then ContactAddresses="$ContactAddresses \n <a data-toggle=\"tooltip\" title=\"Misc\" href=\"$NZ_PUBLIC_MISC\"><i class=\"icon-blank\"></i></a>"; fi
	HtmlHeader=$(cat $NZ_PATH/contact/header.html)
	HtmlFooter=$(cat $NZ_PATH/contact/footer.html)
	echo -e "$HtmlHeader" "$ContactAddresses" "$HtmlFooter" >| "$APACHE_DOCUMENTROOT/contact/index.html"
	_NzFixPermissions
}

_NzRegenHomePage() { #Generate the homepage
	# print html header
	cat "$NZ_PATH/homepage/header.html" | sed "s/nz_replace_host/$NZ_FQDN/g" >| "$APACHE_DOCUMENTROOT/index.html"

	# Print web server title
	pretty_fqdn=$("$NZ_FQDN" | sed "s/\./\.\<br\/\>/g")
	cat "$NZ_PATH/homepage/servername.html" | sed "s/nz_replace_host/$pretty_fqdn/g" >> "$APACHE_DOCUMENTROOT/index.html"

	########### Print HTTPS box TODO: use javascript
	# <!-- Box to switch to HTTPS -->
	# <a class="title" href="https://<?php echo $_SERVER['HTTP_HOST'] ?>" style="background-image:url(img/secure.png); background-color:#000">
	# <div class="app">
	# <h1>HTTPS</h1>
	# <p>Connection sécurisée au site</p>
	# </div>
	# </a>


	for manifest in $(find "$NZ_PATH/webapps/" -name "*.manifest" -type f | xargs readlink -f);
	do
		source "$manifest"
		# for each installed web app, if it is not in the nz_webapp_notshow config array
		if [ -d $APACHE_DOCUMENTROOT/$AppWwwDir && ! $(_ArrayContainsElement "$AppName" "${nz_webapp_notshow[@]}") ]
			# print it's html box
			then cat $NZ_PATH/webapps/$AppName.index.html >> "$APACHE_DOCUMENTROOT/index.html"
		fi
	done


	# print footer
	cat "$NZ_PATH/homepage/footer.html" | sed "s/nz_replace_host/$NZ_FQDN/g" >> "$APACHE_DOCUMENTROOT/index.html"

}






_NzSymlinkWebappDataDirs() { #Create symlinks to zenphoto and Dokuwiki data dirs in the main user's (UID 1000) home directory
	echo "Not yet implemented." #TODO: Not called from anywhere, add this to a menu
}


_NzUserGetName() { #Get system's main user name (assume it was the first user created)
	NZ_USER=$(getent passwd|grep 1000:1000|awk -F":" '{print $1}')
}

_NzGetLANSubnet() { #Get the current LAN IP and subnet
	ip addr show ${nz_net_iface} | egrep "inet " | awk -F" " '{print $2}'
}