#!/bin/bash
#Prosody management menu
source /etc/nodezero/nodezero.conf
set -e

###############################################################################

_NzProsodyGetStatus() { #Get IM server enabled/disabled status
if [[ -f /var/run/prosody/prosody.pid ]]
then PROSODY_STATUS="Enabled"
else PROSODY_STATUS="Disabled"
fi
}

_NzProsodyToggle() { #Enable/disable IM server
if [ ${PROSODY_STATUS} = "Disabled" ]
then rcconf --on prosody --now
else rcconf --off prosody --now #Todo: get rid of rcconf
fi
}

_NzProsodyGetRegistrationsStatus() { #Get new IM accounts registrations allowed/denied status
if [ `grep "allow_registration = true" /etc/prosody/prosody.cfg.lua` ]
then PROSODY_REG_ENABLED="Allowed"
else PROSODY_REG_ENABLED="Not allowed"
fi
}

_NzProsodyAddUser() { #Create new IM account
echo "Please enter the desired username for the new account:"
read PROSODY_NEW_USERNAME
prosodyctl adduser "${PROSODY_NEW_USERNAME}@${NZ_FQDN}"
if [ $? = 0 ]
    then echo "Done. You can now login with an XMPP client. Username: ${PROSODY_NEW_USERNAME} , Domain: ${NZ_FQDN}. Press any key to continue."
read -n 1
fi
}


_NzProsodyGetUserlist() { #Get list of IM accounts on the server
PROSODY_FQDN_STRING=`echo $NZ_FQDN | sed 's/\./\%2e/g'`
PROSODY_ACCOUNT_FILES=`find "/var/lib/prosody/${PROSODY_FQDN_STRING}/accounts" -name "*.dat"`
PROSODY_ACCOUNT_LIST=`for i in ${PROSODY_ACCOUNT_FILES}; do basename $i .dat; done`
}


_NzProsodyDelUser() { #Delete an existing IM account
_NzProsodyGetUserlist
echo "List of accounts on the server:
$PROSODY_ACCOUNT_LIST
Enter the name of the account you want to delete:"
read PROSODY_DELETE_ACCOUNT
prosodyctl deluser "${PROSODY_DELETE_ACCOUNT}@${FQDN}"
}

_NzProsodyChangeUserPassword() { #Change password for an IM account
_NzProsodyGetUserlist
echo "List of accounts on the server:
$PROSODY_ACCOUNT_LIST
Enter the name of the account you want to change the password for:"
read PROSODY_PASSWD_ACCOUNT
prosodyctl passwd "${PROSODY_PASSWD_ACCOUNT}@${FQDN}"
}


###############################################################################

_NzMenuProsody() { #Main prosody IM server menu
until [ "$selection" = "0" ]; do
_NzProsodyGetStatus
_NzProsodyGetRegistrationsStatus
echo "
### XMPP/JABBER SERVER (PROSODY) #############################
 - [1] Status: [$PROSODY_STATUS]
 - [2] New account registration: [$PROSODY_REG_ENABLED]
 - [3] Add a new account
 - [4] Delete an account
 - [5] Change an account password
 - [6] List accounts
 - [0] Back to main Menu
"
     read selection
     case $selection in
         1 ) _NzProsodyToggle;;
         2 ) _NzProsodyToggleResgistrations;; #TODO
         3 ) _NzProsodyAddUser;;
         4 ) _NzProsodyDelUser;;
         5 ) _NzProsodyChangeUserPassword;;
         6 ) _NzProsodyGetUserlist; echo $PROSODY_ACCOUNT_LIST;;
         0 ) exit;;
         * ) echo "Please enter a valid number"
    esac
done
}


_NzMenuProsody