#!/bin/bash
#Description: Apache2 Menu for nodezero (https://telecom.dmz.se/software/nodezero)
#Copyright (c) 2014 nodiscc
#License: MIT (http://opensource.org/licenses/MIT)

_NzMenuApache2() { #TODO
	source ${NZ_PATH}/scripts/NzMenuServices

	selection=
	until [ "$selection" = "0" ]; do
		_NzServiceApacheCheck
	
		if $nz_apache2_installed="no"
		#If apache2 is not installed, show this menu
		then
			echo ""
			echo "## Selected service:"
			echo "Apache web server [Not installed]"
			echo " [I] Install service"
			echo " [0] Back to main menu"
			echo ""
			echo -n "Enter Selection: "
	
			read selection
			case $selection in
		 		I ) #TODO;;
				0 ) return 0;;
				* ) echo "Please enter a valid number"
			esac

		#Else if apache2 is installed, show this menu
		else
			echo ""
			echo "## Selected service:"
			echo "Apache web server [$nz_apache2_status] [$nz_apache2_firewall]"
			echo " [1] $nz_service_toggle_action"
			echo " [2] Firewall: Allow access from Internet"
			echo " [3] Firewall: Allow access from LAN only"
			echo " [4] Firewall: Disallow all access"
			echo " [5] Edit password protected directories"
			echo " [6] Add/manage/remove web applications"
			echo " [7] Regenerate homepage"
			echo ""
			echo " [U] Uninstall service"
			echo " [0] Back to main Menu"
			echo ""
			echo -n "Enter Selection: "

			read selection
			case $selection in
	 		1 ) _NzServiceToggle apache2;;
			2 ) _NzFirewallAllow 80,443 tcp;;
			3 ) _NzFirewallDeny 80,443 tcp;_NzAllowFromLAN 80,443 tcp;;
			4 ) _NzFirewallDeny 80,443 tcp;;
			5 ) #TODO;;
			6 ) #TODO;;
			7 ) _NzRegenHomepage;;
			U ) #TODO;;
			0 ) return 0;;
			* ) echo "Please enter a valid number"
			esac
		fi
	done

}



_NzServiceApacheCheck() { #Checks for apache2 status and network access
	if [ ! -f /etc.init.d/apache2 ]
	#If apache is not installed	
	then
		nz_apache2_installed="no",
		nz_menu_apache2_line=" [1]	Apache web server	[not installed]"

	#If apache is installed
	else
		#Get service status
		service apache2 status >/dev/null
		case "$?" in
		0) nz_apache2_status="running"; nz_service_toggle_action="Disable service";;
		*) nz_apache2_status="stopped"; nz_service_toggle_action="Enable service";;
		esac

		#Check firewall status for service
		#TODO: move this to NzMenuFirewall as a function: _NzFirewallCheck 443
		#TODO: use LAN and VPN netmasks instead of hardcoding 192.168 (_NzGetLANSubnet)
		if [[ $(sudo ufw status numbered | grep "443/tcp                    ALLOW IN    Anywhere") ]]
			then nz_apache2_firewall="Internet access"
		elif [[ $(sudo ufw status numbered | grep "443/tcp                    ALLOW IN    192.168") ]]
			then nz_apache2_firewall="LAN access only"
		else
			nz_apache2_firewall="Blocked"
		fi

		#Build variables for menus
		nz_menu_apache2_line=" [1]	Apache web server	[$nz_apache2_status]	[$nz_apache2_firewall]"
		nz_apache2_installed="yes"
	fi
}