#!/bin/bash
#Tools Menu
source /etc/nodezero/nodezero.conf
set -e

selection=
until [ "$selection" = "0" ]; do
     echo ""
     echo "========== TOOLS MENU =========="
     echo "1 - dfc - display disk usage"
     echo "2 - htop - system monitor"
     echo "3 - ncdu - disk usage analyzer"
     echo "4 - last - display user login history"
     echo "5 - lastb - display failed login attempts"
     echo "6 - nethogs - display network usage by programs"
     echo "7 - iftop - display network usgae by connection"
     echo "8 - ranger - explore filesystem"
     echo "9 - Display system information"
     echo "10 - Edit maintenance message"
     echo "11 - lynis - Security Audit"
     echo "12 - Purge old configuration files"
     echo "13 - Clear packages cache"
     echo "14 - aptitude - manage software packages/updates"
     echo "15 - Update installed software now"
     echo "16 - goaccess - analyze and display web server logs"
     echo "17 - lnav - view system log files"
     echo ""
     echo "0 - Exit program"
     echo ""
     echo -n "Enter Selection:"
     read selection
     echo ""
     case $selection in
         1 ) _NzRunDfc;;
         2 ) _NzRunHtop;;
         3 ) _NzRunNcdu;;
         4 ) _NzRunLast;;
	     5 ) _NzRunLastb;;
	     6 ) _NzRunNethogs;;
	     7 ) _NzRunIftop;;
    	 8 ) _NzRunRanger;;
    	 9 ) _NzShowMotd;;
    	 10 ) _NzEditMotd;;
    	 11 ) _NzRunLynis;;
    	 12 ) _NzAptitudePurge;;
    	 13 ) _NzAptitudeClean;;
    	 14 ) _NzRunAptitude;;
    	 15 ) _NzAptUpgrade;;
    	 16 ) _NzRunGoAccess;;
         17 ) lnav;;
         0 ) exit;;
         * ) echo "Please enter a valid number"
     esac
done