#!/bin/bash
#Description: Services Menu for nodezero (https://telecom.dmz.se/software/nodezero)
#Copyright (c) 2014 nodiscc
#License: MIT (http://opensource.org/licenses/MIT)

source /etc/nodezero/nodezero.conf
set -e

_NzMenuServices() { #Main services menu
	source ${NZ_PATH}/scripts/NzMenuApache2; _NzServiceApacheCheck
	source ${NZ_PATH}/scripts/NzMenuMysql; _NzServiceMysqlCheck
	source ${NZ_PATH}/scripts/NzMenuProsody; _NzServiceProsodyCheck
	source ${NZ_PATH}/scripts/NzMenuSSH; _NzServiceSSHCheck
	source ${NZ_PATH}/scripts/NzMenuTransmission; _NzServiceTransmissionCheck
	source ${NZ_PATH}/scripts/NzMenuMumble; _NzServiceMumbleCheck
	source ${NZ_PATH}/scripts/NzMenuSamba; _NzServiceSambaCheck

	selection=
	until [ "$selection" = "0" ]; do
		echo ""
		echo "################################### SERVICES #############"
		echo "#EDIT	#NAME			#STATUS		#ACCESS"
		echo "$nz_menu_apache2_line"
		echo "$nz_menu_mysql_line"
		echo "$nz_menu_prosody_line"
		echo "$nz_menu_ssh_line"
		echo "$nz_menu_transmission_line"
		echo "$nz_menu_mumble_line"
		echo "$nz_menu_samba_line"
		echo ""
		echo "[Q] Exit ---- [0] Back to Main Menu"
		echo ""
		echo -n "Enter Selection: "

		read selection
		case $selection in
		 1 ) _NzMenuApache2;;
		 2 ) _NzMenuMysql;;
		 3 ) _NzMenuProsody;;
		 4 ) _NzMenuSSH;;
		 5 ) _NzMenuTransmission;;
		 6 ) _NzMenuMumble;;
		 7 ) _NzMenuSamba;;
		 Q ) exit 0;;
		 0 ) return 0;;
		 * ) echo "Please enter a valid number"
		esac
	done
}


_NzServiceToggle() { #Start or stop a service, depending on it's status
	if [ "$nz_service_toggle_action" = "Disable service" ]
		then service $1 stop
		else service $1 start
	fi
}


####### Firewall functions

_NzAllowFromLAN() { #Allow a port to be accessed from the LAN. Usage: _NzAllowFromLAN 135,139,445 tcp
	source "${NZ_PATH}/scripts/NzConfigRoutines"
	ufw allow from $(_NzGetLANSubnet) to any port "$1" proto "$2"
}

_NzFirewallDeny() { #Deny access to a port. Usage: _NzFirewallDeny 80,443 tcp
	ufw deny log $1/$2
}

_NzFirewallAllow() { #Allow all access to a port. Usage: _NzFirewallAllow 80,443 tcp
	ufw allow $1/$2
}


############################################################
### Menu mockups, TODO move this to scripts/NzMenuXxxxx


_NzServiceSambaCheck() { #TODO
}
_NzMenuSamba() { #TODO
#	## Selected service:
#	Samba file sharing [running] [LAN Access only]
#	 [1] Disable service
#	 [2] Firewall: Allow access from Internet
#	 [3] Firewall: Allow access from LAN only
#	 [4] Firewall: Disallow all access
#	 [5] List samba users
#	   [51] Add samba user
#		[SUBMENU] name of new user? (twice) -> (check if it exists, if yes throw error,
#							if no, adduser (unix) (#TODO: options?)
#							(-s /dev/null -m -d /home/xmodulo xmodulo ??)
#							smbpasswd -a,
#							add following section in smb.conf:
							## SAMBA SHARE
							#[$username-share]
							#path = /home/$username (?)
							#available = yes
							#valid users = $username
							#read only = no
							#browseable = yes
							#public = yes
							#writeable = yes
#							run testparm
#							display message on how to connect - smb://localip/$share-name on linux, \\$localip\$share-name on windows)
							
#	   [52] Remove samba user
#	   [53] Change samba passwords
#	    [SUBMENU] What user? (blank to cancel)
#			New password (twice) -> smbpasswd -a username
#	 [6] Set file access permissions
#	   [SUBMENU] if acl fstab flag is not enabled on samba partition (@TODO add setting in nodezero.conf), throw error, return
#          [SUBMENU] What user? (blank to cancel)
#           [SUBMENU] Directories with read-only access (#TODO copy /etc/nodezero/samba/username-ro.conf to temp file,
#							run editor, save, diff with previous file, if changed:
#							for all directories in old file, remove ACLs for this user,
#							apply read/exec ACLs for dirs in new ro.conf
#							apply read-only ACLs for files in new ro.conf)
#           [SUBMENU] Directories with read+write access (edit /etc/nodezero/samba/username-rw.conf
#							same as previous method but set read/write/exec for dirs, rw for files)
#
#	 [U] Uninstall service
#	 [0] Back to main Menu

# FORMAT FOR PERMISSION SETTINGS
# @TODO create these files from at templates when adding samba users. delete it when users are deleted
#### /etc/nodezero/samba/username-ro.txt
## Enter a list of directories which $user will be able to read (only), including subdirectories
## One directory path on each line
#/media/STORAGE/Programs
#/media/STORAGE/Music

#### /etc/nodezero/samba/username-rw.txt
## Enter a list of directories which $user will be able to read and write to including subdirectories
## One directory path on each line
#/media/STORAGE/Downloads
#/media/STORAGE/Torrents

#TODO: quotas: http://xmodulo.com/samba-file-server-windows-clients.html
}


_NzServiceProsodyCheck() { #TODO
}
_NzMenuProsody() { #TODO
#	## Selected service:
#	Prosody XMPP server [stopped]	[Internet access]
#	 [1] Disable service
#	 [2] Firewall: Allow access from Internet
#	 [3] Firewall: Allow access from LAN only
#	 [4] Firewall: Disallow all access
#	 [5] New account registration: [$PROSODY_REG_ENABLED]
#	 [6] List user accounts
#	 [7] Add a new account
#	 [8] Delete an account
#	 [9] Change an account password
#
#	 [U] Uninstall service
#	 [0] Back to main Menu
}


_NzServiceMysqlCheck() { #TODO
}

_NzServiceSSHCheck() { #TODO
}

_NzServiceTransmissionCheck() { #TODO
}

_NzServiceMumbleCheck() { #TODO
}
