#!/bin/bash
#Main Menu
source /etc/nodezero/nodezero.conf
set -e

_NzEditConfig() { #Edit and reload main nodezero config file
    #Note: See also https://packages.debian.org/sid/augeas-tools to edit config files
    $EDITOR ${NZ_CONF_PATH}/nodezero.conf
    source "${NZ_CONF_PATH}/nodezero.conf"
    echo "$NZ_FQDN" >| /etc/hostname
    hostname "$NZ_FQDN"
    _NzRegenContactPage #TODO
    _NzReloadConfig #TODO: (check if paths/values in nodezero.conf are valid) update config files accordingly
}

_NzMenuMain() {
    selection=
    until [ "$selection" = "0" ]; do
         echo ""
         echo "========== NODEZERO MAIN MENU =========="
         echo "1 - Tools Menu"
         echo "2 - User account and permissions menu"
         echo "3 - Backup menu"
         echo "4 - System maintenance and troubleshooting Menu"
         echo "5 - Edit main configuration file"
         echo "6 - Prosody instant messaging server configuration"
         echo "7 - Transmission-daemon bittorrent client/seedbox configuration"
         echo "7 - Other services configuration"
         echo "8 - Power off"
         echo "9 - Reboot"
         echo ""
         echo "0 - Exit program"
         echo ""
         echo -n "Enter Selection:"
         read selection
         echo ""
         case $selection in
             1 ) _NzMenuTools;; #OK
             2 ) _NzMenuUserAccount;; #OK
             3 ) source ${NZ_PATH}/scripts/NzMenuBackup; _NzMenuBackup;; #OK
             4 ) _NzMenuTroubleshooting;; #OK
             5 ) _NzEditConfig;;
             6 ) _NzMenuProsody;; #OK
             7 ) _NzMenuServices;; #OK
             8 ) _NzPoweroff;; #TODO in common.sh
             9 ) _NzReboot;; #TODO in common.sh
             0 ) return 0;;
             * ) echo "Please enter a valid number"
         esac
    done
}