<?php
/*
 * Dokuwiki's Main Configuration File - Local Settings
 * Auto-generated by config plugin
 * Run for user: zerodb
 * Date: Tue, 29 Jan 2013 18:52:05 +0100
 */

$conf['lang'] = 'fr';
$conf['dmode'] = 0775;
$conf['fmode'] = 0664;
$conf['youarehere'] = 1;
$conf['tocminheads'] = '1';
$conf['maxtoclevel'] = '5';
$conf['useacl'] = 1;
$conf['disableactions'] = 'register';
$conf['htmlok'] = 1;
$conf['rss_update'] = 600;
$conf['userewrite'] = '1';

// end auto-generated content
